name: C/C++ CI

on: [push, pull_request]

jobs:
  gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc]
    steps:
    - uses: actions/checkout@v2
    - name: Compile Library
      env:
        CCFLAGS: "-fsanitize=undefined"
      run: |
        ${{ matrix.compiler }} --version
        make test CC=${{ matrix.compiler }}
    - name: Run Unittests
      run: |
        ls dist/
        dist/test
    - name: Calculate Coverage
      run: gcov ./dist/*.gcno
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    # The following should be moved into a seperate action for only pull requests, etc.
    # where you it posts the information into the PR as a comment (optionally?)
    - name: c-linter
      uses: tonybaloney/cppcheck-action@master
      with:
        path: "./src/"
        opts: "--error-exitcode=1 --inline-suppr --enable=warning,performance,information,style"
      # run: cppcheck --error-exitcode=1 --inline-suppr --enable=warning,performance,information,style --template='{file}:{line},{severity},{id},{message}' ./src/
  clang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [clang]
    steps:
    - uses: actions/checkout@v2
    - name: Compile Library
      env:
        CCFLAGS: "-fsanitize=undefined"
      run: |
        ${{ matrix.compiler }} --version
        make test CC=${{ matrix.compiler }}
    - name: Run Unittests
      run: |
        ls dist/
        dist/test
