name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc-4.9, gcc-5, gcc-6, gcc-7, gcc-8, gcc-9, gcc-10, clang-3.9, clang]

    steps:
    - uses: actions/checkout@v2
    - name: Compile Library
      env:
        CC: ${{ matrix.compiler }}
        CCFLAGS: "-fsanitize=undefined"
      run: |
        gcc --version
        make test
    - name: Run Unittests
      run: ./dist/test
    - name: Calculate Coverage
      run: gcov ./dist/*.gcno
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
